// Code generated by gen; DO NOT EDIT.

package cmd

var commands = map[string]struct {
	short string
	long  string
}{
	"bear": {
		short: "Generate Renovate configuration using bear preset",
		long:  "Generate Renovate configuration using bear preset, which same as panda but with prCreation not-pending and prNotPendingHours 1.",
	},
	"eagle": {
		short: "Generate Renovate configuration using eagle preset",
		long:  "Generate Renovate configuration using eagle preset, which same as owl but with prCreation not-pending.",
	},
	"gerbil": {
		short: "Generate Renovate configuration using gerbil preset",
		long:  "Generate Renovate configuration using gerbil preset, which same as hamster but with prCreation not-pending.",
	},
	"gorilla": {
		short: "Generate Renovate configuration using gorilla preset",
		long:  "Generate Renovate configuration using gorilla preset, which same as monkey but with prCreation not-pending.",
	},
	"hamster": {
		short: "Generate Renovate configuration using hamster preset",
		long:  "Generate Renovate configuration using hamster preset, which auto-merges all dependency types and recreates PRs without filtering update types or post-update options.",
	},
	"hare": {
		short: "Generate Renovate configuration using hare preset",
		long:  "Generate Renovate configuration using hare preset, which same as rabbit but with prCreation not-pending.",
	},
	"jaguar": {
		short: "Generate Renovate configuration using jaguar preset",
		long:  "Generate Renovate configuration using jaguar preset, which same as lion but with prCreation not-pending and prNotPendingHours 1.",
	},
	"kangaroo": {
		short: "Generate Renovate configuration using kangaroo preset",
		long:  "Generate Renovate configuration using kangaroo preset, which same as koala but with prCreation not-pending and prNotPendingHours 1.",
	},
	"koala": {
		short: "Generate Renovate configuration using koala preset",
		long:  "Generate Renovate configuration using koala preset, which auto-merges dependencies with pin strategy and npm/pnpm dedupe options.",
	},
	"leopard": {
		short: "Generate Renovate configuration using leopard preset",
		long:  "Generate Renovate configuration using leopard preset, which same as tiger but with prCreation not-pending and prNotPendingHours 1.",
	},
	"lion": {
		short: "Generate Renovate configuration using lion preset",
		long:  "Generate Renovate configuration using lion preset, which auto-merges all dependency types with merge type pr and ignore tests since we don't have any.",
	},
	"monkey": {
		short: "Generate Renovate configuration using monkey preset",
		long:  "Generate Renovate configuration using monkey preset, which auto-merges all updates including indirect dependencies.",
	},
	"mouse": {
		short: "Generate Renovate configuration using mouse preset",
		long:  "Generate Renovate configuration using mouse preset, which same as rat but with prCreation not-pending.",
	},
	"owl": {
		short: "Generate Renovate configuration using owl preset",
		long:  "Generate Renovate configuration using owl preset, which auto-merges and recreates PRs for all update types including replacements.",
	},
	"panda": {
		short: "Generate Renovate configuration using panda preset",
		long:  "Generate Renovate configuration using panda preset, which uses pin range strategy with auto-merging and recreation policies.",
	},
	"penguin": {
		short: "Generate Renovate configuration using penguin preset",
		long:  "Generate Renovate configuration using penguin preset, which auto-merges all dependency types with merge type branch to prevent noisey pull request emails.",
	},
	"rabbit": {
		short: "Generate Renovate configuration using rabbit preset",
		long:  "Generate Renovate configuration using rabbit preset, which auto-merges all dependency types and recreates PRs without filtering update types.",
	},
	"rat": {
		short: "Generate Renovate configuration using rat preset",
		long:  "Generate Renovate configuration using rat preset, which focuses on auto-merging standard updates with no automated testing.",
	},
	"seal": {
		short: "Generate Renovate configuration using seal preset",
		long:  "Generate Renovate configuration using seal preset, which same as penguin but with prCreation not-pending and prNotPendingHours 1.",
	},
	"tiger": {
		short: "Generate Renovate configuration using tiger preset",
		long:  "Generate Renovate configuration using tiger preset, which auto-merges all dependency types with merge type branch to reduce pull request noise.",
	},
}
